### ISSUE TITLE
Process

### ISSUE THREAD

**Issue by DizzyDez** [AlexandraRothenberg/simple-chat-app#8]
# Progress
- [x] Paper Wireframes
  - [x] 404 page
  - [x] Username/Login Page
  - [x] Chat (main) page
  - [x] Members List
  - [x] Notifications
    - [x] Joined
    - [x] Left
- [ ] Interactive Wireframes
  - [ ] 404 page
  - [ ] Chat (main) page
  - [ ] Members List
  - [ ] Notifications
    - [ ] Joined
    - [ ] Left
- [ ] Complete Project
  - [ ] 404 page
  - [ ] Chat (main) page
  - [ ] Members List
  - [ ] Notifications
    - [ ] Joined
    - [ ] Left

# Issues
Completed: Username/Login Screen. 

# Positives :+1:

+ We did it quickly, the layout was simple to figure out. There were multiple options on some of them, and we determined what would be best as a team. 
+ Made sure our site was cohesive across the several pages.

# Improvements :star:

+ We could have done it less last minute, our wireframes were sorta scribbled down and not concrete.

# Request for Feedback :ear:

+ Looks like we're well on our way. 

@AlexandraRothenberg 
@CelesteLavo0118 
@ericadamski

**Comment by CelesteLavo0118** [comment]
# Issues
+ Chat (main) page

# Positives :+1:

+ coordinating between teammates to work on a big projects and making it all work together

# Improvements :star:

+ Updating each other on progress (communication)
+ doing everything last minute (me)

# Request for Feedback :ear:

+ N/A (for now 😄 )

**Comment by AlexandraRothenberg** [comment]
# Issues
Completed: 

+ 404 page
+ Members List
+ Notifications
   + Joined
   + Left

# Positives :+1:

+ Working and coordinating in a group on wireframes.
+ Learning to work on independently pieces of a larger project (bit by bit). 


# Improvements :star:

+ Updating each other on our progresses as a group.

# Request for Feedback :ear:

+ Nothing at this time. (talked in class)

**Comment by ericadamski** [comment]
:+1:
